### ISSUE TITLE
问问题

### ISSUE THREAD

**Issue by Wintersweet0** [yunwei37/os-summer-of-code-daily#1]
请问您在rustlings小练习中做clippy这个文件夹的时候，是怎么样使用到clippy的功能的呢？

我的疑惑在于，我的vscode和命令行都装上了clippy，但是我在运行小练习中的clippy1.rs文件中给出的示例代码时，并没有得到clippy的提示，请问如何看到clippy的提示呢？

**Comment by yunwei37** [comment]
我是使用 rustlings watch 或者 rustlings verify 命令运行所有测试的啦（根据Readme里面的方法来的）

参考 [https://github.com/rust-lang/rustlings#doing-exercises](https://github.com/rust-lang/rustlings#doing-exercises)

**Comment by Wintersweet0** [comment]
多谢！我太粗心了...
