### ISSUE TITLE
又一个问题

### ISSUE THREAD

**Issue by Wintersweet0** [yunwei37/os-summer-of-code-daily#2]
又来打扰您了，可以教一下我rustlings的README的Windows那部分怎么在powershell里输入指令吗（我好菜）
如果不介意的话或许我们可以加一下微信方便聊，我的微信是C276477233

**Comment by yunwei37** [comment]
好呀qwq（我也是萌新...可以一起学习x 

虽然我是在linux上面操作的

**Comment by yunwei37** [comment]
在windows powershell上面不行的话，可以试试这个：

[https://github.com/rust-lang/rustlings#manually](https://github.com/rust-lang/rustlings#manually)
