### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by greatoyster** [yunwei37/os-summer-of-code-daily#3]
可能我的理解有误，PROCESSOR应该是`lock()`而不是`get()`吧

**Comment by yunwei37** [comment]
应该是lock…不过我这边的文档由于来自不同时期的不同分支的版本，所以可能和当前的主分支有一点误差

**Comment by greatoyster** [comment]
我看了源码，发现它用`UnsafeWrapper`代替了当前分支的`Lock`，确实是版本差异的定义不一致造成的（捂脸
